# Generated by Django 6.0.2 on 2026-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=100)),
                ('professor', models.BooleanField(default=False)),
                ('policial', models.BooleanField(default=False)),
                ('bombeiro', models.BooleanField(default=False)),
                ('data_ingresso_servico_publico', models.DateField()),
                ('data_ingresso_cargo', models.DateField()),
                ('tempo_contribuicao', models.FloatField()),
                ('tempo_servico_publico', models.FloatField()),
                ('tempo_carreira', models.FloatField()),
                ('tempo_cargo', models.FloatField()),
                ('salario_atual', models.FloatField()),
            ],
        ),
    ]
