# Generated by Django 6.0.2 on 2026-03-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_atual', models.CharField(choices=[('servidor', 'Servidor Público'), ('professor', 'Professor'), ('militar', 'Policial / Bombeiro')], max_length=20)),
                ('data_ingresso_servico_publico', models.DateField(blank=True, null=True)),
                ('data_ingresso_cargo', models.DateField(blank=True, null=True)),
                ('data_ingresso_carreira', models.DateField(blank=True, null=True)),
                ('tempo_contribuicao', models.IntegerField(default=0)),
                ('tempo_servico_publico_dias', models.IntegerField(default=0)),
                ('tempo_carreira', models.IntegerField(default=0)),
                ('tempo_cargo', models.IntegerField(default=0)),
                ('tempo_magisterio', models.IntegerField(default=0)),
                ('tempo_atividade_policial', models.IntegerField(default=0)),
                ('tempo_atividade_especial', models.IntegerField(default=0)),
                ('invalidez', models.BooleanField(default=False)),
                ('deficiencia', models.BooleanField(default=False)),
                ('grau_deficiencia', models.CharField(blank=True, choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], max_length=10, null=True)),
                ('direito_adquirido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Servidor',
        ),
    ]
