# Generated by Django 6.0.2 on 2026-03-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='Brasileiro', max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('senha_gov', models.CharField(blank=True, help_text='Senha GOV.BR (uso interno)', max_length=100, null=True)),
                ('cargo_atual', models.CharField(choices=[('servidor', 'Servidor Público'), ('professor', 'Professor'), ('militar', 'Policial / Bombeiro')], max_length=20)),
                ('data_ingresso_servico_publico', models.DateField(blank=True, null=True)),
                ('data_ingresso_cargo', models.DateField(blank=True, null=True)),
                ('data_ingresso_carreira', models.DateField(blank=True, help_text='Usado para regras de carreira', null=True)),
                ('tempo_contribuicao', models.IntegerField(default=0, help_text='Tempo total de contribuição em dias')),
                ('tempo_servico_publico_dias', models.IntegerField(default=0, help_text='Tempo no serviço público em dias')),
                ('tempo_carreira', models.IntegerField(default=0, help_text='Tempo na carreira em dias')),
                ('tempo_cargo', models.IntegerField(default=0, help_text='Tempo no cargo atual em dias')),
                ('tempo_magisterio', models.IntegerField(default=0, help_text='Tempo em funções de magistério (dias)')),
                ('tempo_atividade_policial', models.IntegerField(default=0, help_text='Tempo em atividade policial')),
                ('tempo_atividade_especial', models.IntegerField(default=0, help_text='Tempo especial (dias)')),
                ('invalidez', models.BooleanField(default=False)),
                ('deficiencia', models.BooleanField(default=False)),
                ('grau_deficiencia', models.CharField(blank=True, choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], max_length=10, null=True)),
                ('direito_adquirido', models.BooleanField(default=False, help_text='Possuía direito adquirido antes da EC 103')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
