# Generated by Django 6.0.2 on 2026-02-27 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cargo',
            new_name='cargo_efetivo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_ingresso_rpps',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha_gov',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
