# Generated by Django 6.0.2 on 2026-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cep_alter_cliente_data_ingresso_carreira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao', 'União Estável')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='orgao_responsavel',
            field=models.CharField(blank=True, help_text='Ex: SPPREV, IPRC Rio Claro, DER, Prefeitura...', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
