# Generated by Django 6.0.2 on 2026-03-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_cargo_cliente_cargo_efetivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_ingresso_rpps',
            new_name='data_ingresso',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cargo_efetivo',
            new_name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='senha_gov',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cargo_atual',
            field=models.CharField(default='Servidor Público', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='Servidor Público', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(default='Servidor Público', max_length=20),
            preserve_default=False,
        ),
    ]
