# Generated by Django 6.0.2 on 2026-03-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_estado_civil_cliente_orgao_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='orgao_responsavel',
            field=models.CharField(blank=True, choices=[('secretaria municipal de limeira', 'SECRETARIA MUNICIPAL DE LIMEIRA'), ('secretaria municipal de piracicaba', 'SECRETARIA MUNICIAL DE PIRACICABA'), ('secretaria municipal de sao carlos', 'SECRETARIA MUNICIAL DE SÃO CARLOS'), ('secretaria municipal de pirassununga', 'SECRETARIA MUNICIAL DE PIRASSUNINGA'), ('secretaria municipal de sumare', 'SECRETARIA MUNICIAL DE SUMARE'), ('secretaria municipal de sao paulo', 'SECRETARIA MUNICIAL DE SÃO PAULO'), ('secretaria municipal de americana', 'SECRETARIA MUNICIAL DE AMERICANA'), ('secretaria municipal de araraquara', 'SECRETARIA MUNICIAL DE ARARAQUARA'), ('secretaria municipal de campinas', 'SECRETARIA MUNICIAL DE CAMPINAS'), ('secretaria municipal de capivari', 'SECRETARIA MUNICIAL DE CAPIVARI'), ('secretaria municipal de jau', 'SECRETARIA MUNICIAL DE SÃO JAU'), ('secretaria municipal de mogi mirim', 'SECRETARIA MUNICIAL DE MOGI MIRIM')], max_length=200, null=True),
        ),
    ]
