# Generated by Django 6.0.2 on 2026-03-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_data_ingresso_rpps_cliente_data_ingresso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cargo_atual',
            field=models.CharField(choices=[('professor', 'Professor'), ('servidor', 'Servidor Público'), ('militar', 'Policial / Bombeiro')], max_length=20),
        ),
    ]
