# Generated by Django 6.0.2 on 2026-03-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_cargo_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cargo_atual',
            field=models.CharField(choices=[('servidor', 'Servidor Público'), ('professor', 'Professor'), ('militar', 'Policial / Bombeiro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
