# Generated by Django 6.0.2 on 2026-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_remove_cliente_criado_em_alter_cliente_cargo_atual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_ingresso',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rg',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_ingresso_cargo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_ingresso_servico_publico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='invalidez',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tempo_atividade_especial',
            field=models.IntegerField(default=0, help_text='Tempo em anos de atividade policial ou especial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tempo_cargo',
            field=models.IntegerField(default=0, help_text='Tempo em anos no cargo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tempo_carreira',
            field=models.IntegerField(default=0, help_text='Tempo em anos na carreira'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cargo_atual',
            field=models.CharField(choices=[('servidor', 'Servidor Público'), ('professor', 'Professor'), ('militar', 'Policial/Bombeiro')], max_length=20),
        ),
    ]
