# Generated by Django 6.0.2 on 2026-03-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_rename_nome_completo_cliente_nome_remove_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha_gov',
            field=models.CharField(blank=True, help_text='Senha de acesso ao GOV.BR (uso interno do escritório)', max_length=100, null=True),
        ),
    ]
