# Generated by Django 6.0.2 on 2026-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_cpf_cliente_endereco_cliente_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tempo_atividade_especial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tempo_cargo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tempo_carreira',
            field=models.IntegerField(default=0),
        ),
    ]
