# Generated by Django 6.0.2 on 2026-03-05 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_tempo_atividade_especial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cargo_atual',
            field=models.CharField(choices=[('servidor', 'Servidor Público'), ('professor', 'Professor'), ('militar', 'Policial / Bombeiro')], max_length=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_ingresso_cargo',
            field=models.DateField(blank=True, null=True, verbose_name='Ingresso no cargo atual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_ingresso_servico_publico',
            field=models.DateField(blank=True, null=True, verbose_name='Ingresso no serviço público'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='invalidez',
            field=models.BooleanField(default=False, verbose_name='Possui invalidez?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tempo_atividade_especial',
            field=models.IntegerField(default=0, help_text='Tempo especial em dias'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tempo_cargo',
            field=models.IntegerField(default=0, help_text='Tempo no cargo atual (dias)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tempo_carreira',
            field=models.IntegerField(default=0, help_text='Tempo total na carreira (dias)'),
        ),
    ]
